# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
# configure our local APT Cache Server
sudo cp /vagrant/30autoproxy /etc/apt/apt.conf.d/30autoproxy


SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "ubuntu-client.datacenter.local"

  #config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.provision "shell", inline: $script
end
